api_server:
  http:
    port: 5000
  logging:
    access:
      enabled: true
      # whether to log the size of the request body
      request_content_length: true
      # whether to log the content type of the request
      request_content_type: true
      # whether to log the content length of the response
      response_content_length: true
      # whether to log the content type of the response
      response_content_type: true